###
GET http://localhost:9000/api/usuarios HTTP/1.1

###

GET http://localhost:9000/api/equipo HTTP/1.1


###
POST http://localhost:9000/api/usuarios HTTP/1.1
Content-Type: application/json

 {
    "usu_id":"18",
    "usu_email": "admin",
    "usu_clave": "admin",
    "usu_nombres": "admint",
    "usu_apellidos": "Potes"
  }

###
POST http://localhost:9000/api/equipo HTTP/1.1
Content-Type: application/json

{
    "equi_id": 5,
    "equi_nombre": "Calis"
  }


###
PUT http://localhost:9000/api/usuarios/usu_id/1 HTTP/1.1
Content-Type: application/json

{
    "usu_email": "angelpotes@gmail.com",
    "usu_clave": "123456222sd",
    "usu_nombres": "miguel angel",
    "usu_apellidos": "Potes"
}

###
PUT http://localhost:9000/api/equipo/equi_id/4 HTTP/1.1
Content-Type: application/json

{
    "equi_id": 4,
    "equi_nombre": "DDdD"
  }

###
DELETE http://localhost:9000/api/usuarios/usu_id/10 HTTP/1.1



### 
GET http://localhost:9000/api/marcadores HTTP/1.1

###
POST http://localhost:9000/api/marcadores HTTP/1.1
header name: header value

content

